version: '3.9'

services:
  postgres:
    image: phidata/pgvector:16
    container_name: pgvector
    restart: always
    environment:
      POSTGRES_DB: ai
      POSTGRES_USER: ai
      POSTGRES_PASSWORD: ai
      
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5532:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres

volumes:
 postgres-data:
 pgadmin_data:
